# Generated by Django 5.1.1 on 2024-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testclass',
            name='hour',
            field=models.TimeField(choices=[]),
        ),
    ]
