# Generated by Django 5.1.1 on 2024-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_alter_testclass_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='phone',
            field=models.CharField(default='1125254545', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testclass',
            name='hour',
            field=models.TimeField(),
        ),
    ]
