# Generated by Django 5.1.1 on 2024-10-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_testclass_phone_alter_testclass_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sabado'), ('domingo', 'Domingo')], max_length=10)),
                ('hour', models.CharField(choices=[('8:00', '8hs'), ('9:00', '9hs'), ('15:00', '15hs'), ('18:00', '18hs'), ('19:15', '19hs')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='testclass',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.hours'),
        ),
    ]
