# Generated by Django 5.1.1 on 2024-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_hours_alter_testclass_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='hour',
            field=models.CharField(choices=[('8:00', '8hs'), ('9:00', '9hs'), ('10:00', '10hs'), ('12:00', '12hs'), ('14:00', '14hs'), ('15:00', '15hs'), ('18:00', '18hs'), ('19:15', '19hs'), ('0', 'what the fak?'), ('0', 'not classes buddy'), ('0', 'are u sick buddy')], max_length=5),
        ),
    ]
