# Generated by Django 5.1.1 on 2024-10-09 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='first_name',
            field=models.CharField(default='Esteban', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='last_name',
            field=models.CharField(default='Alonzo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rm',
            name='user',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.CASCADE, to='data.persona'),
            preserve_default=False,
        ),
    ]
