# Generated by Django 5.1.1 on 2024-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_persona_created_on_persona_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm',
            name='paralel_dips',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rm',
            name='pull_up',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rm',
            name='skater_squat',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
