# Generated by Django 5.1.1 on 2024-10-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rm_paralel_dips_rm_pull_up_rm_skater_squat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rm',
            name='skater_squat',
        ),
        migrations.AddField(
            model_name='rm',
            name='paralel_dips_weight',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rm',
            name='pull_up_weight',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
