# Generated by Django 5.1.1 on 2024-10-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rm_date_of_medition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfMedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_medition', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='age',
            field=models.IntegerField(default='20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sex',
            field=models.CharField(default='undefined', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_weight', models.IntegerField(blank=True, null=True)),
                ('pull_up', models.IntegerField(blank=True, null=True)),
                ('pull_up_weight', models.IntegerField(blank=True, null=True)),
                ('paralel_dips', models.IntegerField(blank=True, null=True)),
                ('paralel_dips_weight', models.IntegerField(blank=True, null=True)),
                ('skater_squat', models.IntegerField(blank=True, null=True)),
                ('skater_squat_weight', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
            ],
        ),
        migrations.CreateModel(
            name='FullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.dateofmedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
                ('rms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.rmdata')),
            ],
        ),
        migrations.DeleteModel(
            name='Rm',
        ),
    ]
