# Generated by Django 5.1.1 on 2024-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_dateofmedition_persona_age_persona_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmdata',
            name='paralel_dips_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmdata',
            name='pull_up_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmdata',
            name='skater_squat_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
