# Generated by Django 5.1.1 on 2024-10-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_rmdata_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmdata',
            name='date',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.PROTECT, to='data.dateofmedition'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FullData',
        ),
    ]
