# Generated by Django 5.1.1 on 2024-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rmdata_date_delete_fulldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'UNDEFINED')], max_length=1),
        ),
    ]
