# Generated by Django 5.1.1 on 2024-10-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_persona_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RmData',
            new_name='PrData',
        ),
    ]
