# Generated by Django 5.1.1 on 2024-11-04 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_rename_rmdata_prdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL, verbose_name='username'),
            preserve_default=False,
        ),
    ]
