# Generated by Django 5.1.1 on 2024-11-05 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_persona_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
