# Generated by Django 5.1.1 on 2024-11-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_persona_created_on_remove_persona_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdata',
            name='name',
            field=models.CharField(default='mugiwaras', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.persona'),
        ),
    ]
