# Generated by Django 5.1.1 on 2024-11-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_prdata_name_alter_prdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prdata',
            name='user',
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.prdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
            ],
        ),
    ]
