# Generated by Django 5.1.1 on 2024-10-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wod_type', models.CharField(choices=[('Pull Horizontal', 'Pull Horizontal'), ('Pull Vertical', 'Pull Vertical'), ('Push Básico', 'Push Básico'), ('Legs Posterior', 'Legs Posterior'), ('Legs anterior', 'Legs anterior'), ('Abdominales', 'Abdominales'), ('Plancha', 'Plancha'), ('FrontLever', 'FrontLever'), ('Resistencia', 'Resistencia'), ('Movilidad', 'Movilidad')], max_length=25)),
                ('difficult', models.CharField(choices=[('1', 'Super Principiante'), ('2', 'Principiante'), ('3', 'Basico'), ('4', 'Duro'), ('5', 'Posible'), ('6', 'Dificil'), ('7', 'Muy dificil'), ('8', 'Profesional'), ('9', 'Elite'), ('10', 'Imposible')], max_length=25)),
            ],
        ),
    ]
